version: '3.1'

services:

  db:
    container_name: mysql8
    image: mysql:8.0.35
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - /var/lib/mysql8:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nottherealPassword123!
    ports:
      - 13306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080