# noinspection SqlNoDataSourceInspectionForFile

DROP TABLE MEMBERS;

CREATE TABLE MEMBERS (
    ID                         INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBERSHIP_NUMBER          INT         NOT NULL,
    MEMBERSHIP_TYPE            VARCHAR(50) NOT NULL,
    STATUS                     VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    FORENAME                   VARCHAR(50) NOT NULL,
    SURNAME                    VARCHAR(50) NOT NULL,
    PAYER_TYPE                 VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    JOIN_DATE                  DATE,
    LEAVE_DATE                 DATE,
    EMAIL                      VARCHAR(255),
    LANDLINE_NUMBER            VARCHAR(50),
    MOBILE_NUMBER              VARCHAR(50),
    CARD_REQUEST_DATE          DATE,
    CARD_ISSUED_DATE           DATE,
    WELCOME_LETTER_ISSUED_DATE DATE,
    COMMENTS                   VARCHAR(2000),
    IS_ELIGIBLE_FOR_DRAW       BOOLEAN NOT NULL DEFAULT FALSE,
    EMAIL_OPT_OUT              BOOLEAN NOT NULL DEFAULT FALSE,
    DECEASED                   BOOLEAN NOT NULL DEFAULT FALSE,
    ARCHIVED                   BOOLEAN NOT NULL DEFAULT FALSE
);,

DROP TABLE ADDRESSES;

CREATE TABLE ADDRESSES (
    ID             INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(255),
    ADDRESS_LINE_3 VARCHAR(255),
    TOWN           VARCHAR(255) NOT NULL,
    REGION         VARCHAR(50)  NOT NULL,
    POSTCODE       VARCHAR(10),
    COUNTRY        VARCHAR(50),
    IS_ACTIVE      BOOLEAN,
    MEMBER_ID      INT          NOT NULL REFERENCES MEMBERS(ID),
    ARCHIVED       BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE PAYMENTS;

CREATE TABLE PAYMENTS (
    ID                 INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_DATE       DATE          NOT NULL,
    PAYMENT_AMOUNT     DECIMAL(10,2) NOT NULL,
    CREDIT_REFERENCE   VARCHAR(200),
    NAME               VARCHAR(200),
    CREDITED_ACCOUNT   VARCHAR(50),
    MEMBER_ID          INT REFERENCES MEMBERS(ID),
    IS_LOTTERY_PAYMENT BOOLEAN NOT NULL DEFAULT TRUE,
    COMMENTS           VARCHAR(2000),
    ARCHIVED           BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE PAYMENT_REFERENCES;

CREATE TABLE PAYMENT_REFERENCES (
    ID        INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REFERENCE VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN      NOT NULL,
    NAME      VARCHAR(255),
    MEMBER_ID INT          NOT NULL REFERENCES MEMBERS(ID)
);

DROP TABLE LOTTERY_DRAWS;

CREATE TABLE LOTTERY_DRAWS (
    ID           INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DRAW_DATE    DATE NOT NULL,
    NAME         VARCHAR(255),
    LOTTERY_DATE DATE,
    DRAW_MASTER  VARCHAR(255)
);

DROP TABLE PRIZES;

CREATE TABLE PRIZES (
    ID                   INT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRIZE                VARCHAR(1000),
    LOTTERY_DRAW_ID      INT     NOT NULL REFERENCES LOTTERY_DRAWS(ID),
    WINNER_ID            INT REFERENCES MEMBER(ID),
    PRIZE_COLLECTED      BOOLEAN NOT NULL,
    PRIZE_COLLECTED_DATE DATE
);

DROP TABLE NOTIFICATIONS;

CREATE TABLE NOTIFICATIONS (
  ID          INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EVENT_TYPE  VARCHAR(50)   NOT NULL,
  EVENT_DATE  DATE          NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL
);

DROP TABLE SECURITY_SUBJECTS;

CREATE TABLE SECURITY_SUBJECTS (
  ID                     INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FORENAME               VARCHAR(100) NOT NULL,
  SURNAME                VARCHAR(100) NOT NULL,
  USERNAME               VARCHAR(100) NOT NULL,
  PASSWORD               VARCHAR(100) NOT NULL,
  FAILED_LOGIN_ATTEMPTS  INT          NOT NULL DEFAULT 0,
  ACCOUNT_LOCKED         BOOLEAN      NOT NULL DEFAULT FALSE,
  PASSWORD_TO_BE_CHANGED BOOLEAN      NOT NULL DEFAULT FALSE,
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`)
);

DROP TABLE EVENT_LOG;

CREATE TABLE EVENT_LOG (
  ID         INT          NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  MESSAGE    VARCHAR(250) NOT NULL,
  EVENT_DATE TIMESTAMP    NOT NULL DEFAULT NOW()
);

DROP TABLE CONFIGURATION;

CREATE TABLE CONFIGURATION (
  ID            INT          NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  NAME          VARCHAR(250) NOT NULL,
  STRING_VALUE  VARCHAR(250),
  BOOLEAN_VALUE BOOLEAN,
  DATE_VALUE    TIMESTAMP
);

DROP TABLE REPORTS;

CREATE TABLE REPORTS (
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  REPORT_DATE DATE         NOT NULL,
  INT_VALUE   INT          NOT NULL
);

CREATE VIEW INELIGIBLE_FOR_DRAW_VW AS
SELECT m.id member_id, m.MEMBERSHIP_NUMBER, m.FORENAME, m.SURNAME, m.email, m.LANDLINE_NUMBER, m.MOBILE_NUMBER, m.PAYER_TYPE, m.JOIN_DATE, p.PAYMENT_AMOUNT, MAX(p.PAYMENT_DATE) LAST_PAYMENT
FROM members m, payments p
WHERE status = 'Open'
AND IS_ELIGIBLE_FOR_DRAW = FALSE
AND p.member_id = m.id
GROUP BY m.id, m.MEMBERSHIP_NUMBER, m.FORENAME, m.SURNAME, m.email, m.LANDLINE_NUMBER, m.MOBILE_NUMBER, m.PAYER_TYPE, m.JOIN_DATE, p.PAYMENT_AMOUNT
ORDER BY MAX(p.PAYMENT_DATE) DESC;

CREATE INDEX MEMBER_ADDRESS_IDX ON ADDRESSES (MEMBER_ID);

CREATE INDEX ADDRESS_IS_ACTIVE_IDX ON ADDRESSES(IS_ACTIVE);

CREATE INDEX ADDRESS_ARCHIVED_IDX ON ADDRESSES(ARCHIVED);

CREATE INDEX MEMBER_PRIZES_IDX ON PRIZES (WINNER_ID);

CREATE INDEX PRIZES_DRAW_ID_IDX ON PRIZES (LOTTERY_DRAW_ID);

CREATE INDEX MEMBER_REFERENCES_IDX ON PAYMENT_REFERENCES (MEMBER_ID);

CREATE INDEX PAYMENT_REFERENCES_ACTIVE_IDX ON PAYMENT_REFERENCES (IS_ACTIVE);

CREATE INDEX MEMBER_PAYMENTS_IDX ON PAYMENTS (MEMBER_ID);

CREATE UNIQUE INDEX MEMBER_MEMBERSHIP_NUMBER ON MEMBERS (MEMBERSHIP_NUMBER);

CREATE INDEX PAYMENT_DATE_IDX ON PAYMENTS (PAYMENT_DATE);

CREATE INDEX PAYMENT_REFERENCE_IDX ON PAYMENTS (CREDIT_REFERENCE);

CREATE INDEX PAYMENT_ARCHIVED_IDX ON PAYMENTS (ARCHIVED);

CREATE INDEX MEMBER_SURNAME_IDX ON MEMBERS (SURNAME);

CREATE INDEX MEMBER_FORENAME_IDX ON MEMBERS (FORENAME);

CREATE INDEX MEMBER_TYPE_IDX ON MEMBERS (MEMBERSHIP_TYPE);

CREATE INDEX MEMBER_STATUS_IDX ON MEMBERS (STATUS);

CREATE INDEX MEMBER_IS_ELIGIBLE_IDX  ON MEMBERS (IS_ELIGIBLE_FOR_DRAW);

CREATE INDEX MEMBER_ARCHIVED_IDX  ON MEMBERS (ARCHIVED);

CREATE INDEX SECURITY_SUBJECT_NAME_IDX ON SECURITY_SUBJECTS (USERNAME);

CREATE INDEX PAYMENT_IS_LOTTERY_IDX ON PAYMENTS (IS_LOTTERY_PAYMENT);

CREATE INDEX REPORTS_REPORT_DATE_IDX ON REPORTS (REPORT_DATE);

CREATE INDEX CONFIGURATON_NAME_IDX ON CONFIGURATION(NAME);

CREATE INDEX LOTTERY_DRAWS_DATE_IDX ON LOTTERY_DRAWS(LOTTERY_DATE);